"""PumpAhead — Predictive heating/cooling controller with RC thermal models."""

from pumpahead.building_profiles import (
    BUILDING_PROFILES,
    HUBERT_ROOMS,
    heavy_construction,
    hubert_real,
    leaky_old_house,
    thin_screed,
    well_insulated,
)
from pumpahead.config import (
    BuildingParams,
    ControllerConfig,
    CWUCycle,
    RoomConfig,
    SimScenario,
)
from pumpahead.cross_validation import (
    DEFAULT_HORIZONS,
    DEFAULT_OVERFITTING_THRESHOLD,
    CrossValidationResult,
    HorizonRMSE,
    cross_validate,
    cross_validate_rooms,
)
from pumpahead.disturbance_vector import (
    MPC_DT_SECONDS,
    MPC_HORIZON_STEPS,
    DisturbanceBuilder,
    InternalGainProfile,
)
from pumpahead.estimator import KalmanEstimator
from pumpahead.identification_report import (
    DEFAULT_RMSE_PASS_THRESHOLD,
    DEFAULT_RMSE_REIDENTIFICATION_THRESHOLD,
    IdentificationReport,
    QualityMonitor,
    RoomReport,
    plot_predicted_vs_measured,
    plot_residuals,
    plot_rmse_over_time,
)
from pumpahead.identifier import IdentificationResult, RCIdentifier
from pumpahead.metrics import (
    SimMetrics,
    assert_comfort,
    assert_energy_vs_baseline,
    assert_floor_temp_safe,
    assert_no_opposing_action,
    assert_no_priority_inversion,
)
from pumpahead.model import ModelOrder, RCModel, RCParams
from pumpahead.scenarios import (
    PARAMETRIC_SWEEPS,
    SCENARIO_LIBRARY,
    cold_snap,
    cwu_heavy,
    extreme_cold,
    full_year_2025,
    hot_july,
    insulation_sweep,
    rapid_warming,
    screed_sweep,
    solar_overshoot,
    steady_state,
)
from pumpahead.sensor_noise import SensorNoise
from pumpahead.simulated_room import SimulatedRoom
from pumpahead.simulation_log import SimRecord, SimulationLog
from pumpahead.simulator import (
    Actions,
    BuildingSimulator,
    HeatPumpMode,
    Measurements,
    SplitMode,
)
from pumpahead.solar import (
    EphemerisCalculator,
    Orientation,
    SolarGainModel,
    WindowConfig,
)
from pumpahead.solar_gti import (
    GTIModel,
    erbs_decomposition,
    extraterrestrial_horizontal,
)
from pumpahead.weather import (
    ChannelProfile,
    CSVConfig,
    CSVParseError,
    CSVWeather,
    OpenMeteoHistorical,
    ProfileKind,
    SyntheticWeather,
    WeatherAPIError,
    WeatherDataError,
    WeatherPoint,
    WeatherRangeError,
    WeatherSource,
)

__version__ = "0.1.0"

__all__ = [
    "Actions",
    "BUILDING_PROFILES",
    "DEFAULT_RMSE_PASS_THRESHOLD",
    "DEFAULT_RMSE_REIDENTIFICATION_THRESHOLD",
    "assert_comfort",
    "assert_energy_vs_baseline",
    "assert_floor_temp_safe",
    "assert_no_opposing_action",
    "assert_no_priority_inversion",
    "BuildingParams",
    "BuildingSimulator",
    "ChannelProfile",
    "ControllerConfig",
    "CrossValidationResult",
    "CSVConfig",
    "CSVParseError",
    "CSVWeather",
    "CWUCycle",
    "cross_validate",
    "cross_validate_rooms",
    "DEFAULT_HORIZONS",
    "DEFAULT_OVERFITTING_THRESHOLD",
    "DisturbanceBuilder",
    "GTIModel",
    "EphemerisCalculator",
    "HUBERT_ROOMS",
    "HeatPumpMode",
    "HorizonRMSE",
    "IdentificationReport",
    "InternalGainProfile",
    "IdentificationResult",
    "KalmanEstimator",
    "Measurements",
    "MPC_DT_SECONDS",
    "MPC_HORIZON_STEPS",
    "ModelOrder",
    "OpenMeteoHistorical",
    "Orientation",
    "PARAMETRIC_SWEEPS",
    "ProfileKind",
    "QualityMonitor",
    "RCIdentifier",
    "RCModel",
    "RCParams",
    "RoomConfig",
    "RoomReport",
    "SCENARIO_LIBRARY",
    "SensorNoise",
    "SimMetrics",
    "SimRecord",
    "SimScenario",
    "SimulatedRoom",
    "SimulationLog",
    "SolarGainModel",
    "SplitMode",
    "SyntheticWeather",
    "WeatherAPIError",
    "WeatherDataError",
    "WeatherPoint",
    "WeatherRangeError",
    "WeatherSource",
    "WindowConfig",
    "__version__",
    "erbs_decomposition",
    "extraterrestrial_horizontal",
    "cold_snap",
    "cwu_heavy",
    "extreme_cold",
    "full_year_2025",
    "heavy_construction",
    "hot_july",
    "hubert_real",
    "insulation_sweep",
    "leaky_old_house",
    "plot_predicted_vs_measured",
    "plot_residuals",
    "plot_rmse_over_time",
    "rapid_warming",
    "screed_sweep",
    "solar_overshoot",
    "steady_state",
    "thin_screed",
    "well_insulated",
]
