"""PumpAhead — Predictive heating/cooling controller with RC thermal models."""

from pumpahead.ab_testing import (
    ABReport,
    ABTestRunner,
    ControllerAdapter,
    MPCAdapter,
    PIDAdapter,
    plot_overlay,
)
from pumpahead.building_profiles import (
    BUILDING_PROFILES,
    HUBERT_ROOMS,
    heavy_construction,
    hubert_real,
    leaky_old_house,
    thin_screed,
    well_insulated,
)
from pumpahead.config import (
    BuildingParams,
    ControllerConfig,
    CWUCycle,
    RoomConfig,
    SimScenario,
)
from pumpahead.controller import PIDController, PumpAheadController
from pumpahead.cross_validation import (
    DEFAULT_HORIZONS,
    DEFAULT_OVERFITTING_THRESHOLD,
    CrossValidationResult,
    HorizonRMSE,
    cross_validate,
    cross_validate_rooms,
)
from pumpahead.cwu_coordinator import (
    CWU_HEAVY,
    CWU_STANDARD,
    CWU_WORST_CASE,
    CWUCoordinator,
)
from pumpahead.disturbance_vector import (
    MPC_DT_SECONDS,
    MPC_HORIZON_STEPS,
    DisturbanceBuilder,
    InternalGainProfile,
)
from pumpahead.estimator import KalmanEstimator
from pumpahead.identification_report import (
    DEFAULT_RMSE_PASS_THRESHOLD,
    DEFAULT_RMSE_REIDENTIFICATION_THRESHOLD,
    IdentificationReport,
    QualityMonitor,
    RoomReport,
    plot_predicted_vs_measured,
    plot_residuals,
    plot_rmse_over_time,
)
from pumpahead.identifier import IdentificationResult, RCIdentifier
from pumpahead.log_serializer import (
    load_json,
    load_pickle,
    save_json,
    save_pickle,
)
from pumpahead.metrics import (
    SimMetrics,
    assert_comfort,
    assert_energy_vs_baseline,
    assert_floor_temp_safe,
    assert_no_opposing_action,
    assert_no_priority_inversion,
)
from pumpahead.model import ModelOrder, RCModel, RCParams
from pumpahead.optimizer import (
    MPCConfig,
    MPCController,
    MPCInfeasibleError,
    MPCOptimizer,
    MPCResult,
    RecedingHorizonResult,
)
from pumpahead.replay import create_app as create_replay_app
from pumpahead.safety_rules import (
    DEFAULT_SAFETY_RULES,
    S1_FLOOR_OVERHEAT,
    S2_CONDENSATION,
    S3_EMERGENCY_HEAT,
    S4_EMERGENCY_COOL,
    S5_WATCHDOG,
    SafetyAction,
    SafetyEvaluator,
    SafetyRule,
    SafetyRuleResult,
    SensorSnapshot,
)
from pumpahead.scenarios import (
    PARAMETRIC_SWEEPS,
    SCENARIO_LIBRARY,
    cold_snap,
    cwu_heavy,
    cwu_with_splits,
    dual_source_cold_snap,
    dual_source_steady_state,
    extreme_cold,
    full_year_2025,
    hot_july,
    insulation_sweep,
    priority_inversion_stress,
    rapid_warming,
    screed_sweep,
    solar_overshoot,
    steady_state,
)
from pumpahead.sensor_noise import SensorNoise
from pumpahead.simulated_room import SimulatedRoom
from pumpahead.simulation_log import SimRecord, SimulationLog
from pumpahead.simulator import (
    Actions,
    BuildingSimulator,
    HeatPumpMode,
    Measurements,
    SplitMode,
)
from pumpahead.solar import (
    EphemerisCalculator,
    Orientation,
    SolarGainModel,
    WindowConfig,
)
from pumpahead.solar_gti import (
    GTIModel,
    erbs_decomposition,
    extraterrestrial_horizontal,
)
from pumpahead.split_coordinator import SplitCoordinator, SplitDecision
from pumpahead.visualization import (
    generate_plots,
    plot_dashboard,
    plot_energy,
    plot_room_temperatures,
    plot_splits,
    plot_valves,
    plot_weather,
)
from pumpahead.weather import (
    ChannelProfile,
    CSVConfig,
    CSVParseError,
    CSVWeather,
    OpenMeteoHistorical,
    ProfileKind,
    SyntheticWeather,
    WeatherAPIError,
    WeatherDataError,
    WeatherPoint,
    WeatherRangeError,
    WeatherSource,
)

__version__ = "0.1.0"

__all__ = [
    "ABReport",
    "ABTestRunner",
    "Actions",
    "BUILDING_PROFILES",
    "DEFAULT_RMSE_PASS_THRESHOLD",
    "DEFAULT_RMSE_REIDENTIFICATION_THRESHOLD",
    "DEFAULT_SAFETY_RULES",
    "assert_comfort",
    "assert_energy_vs_baseline",
    "assert_floor_temp_safe",
    "assert_no_opposing_action",
    "assert_no_priority_inversion",
    "BuildingParams",
    "BuildingSimulator",
    "ControllerAdapter",
    "ChannelProfile",
    "ControllerConfig",
    "CrossValidationResult",
    "PIDController",
    "PumpAheadController",
    "CSVConfig",
    "CSVParseError",
    "CSVWeather",
    "CWUCoordinator",
    "CWUCycle",
    "CWU_HEAVY",
    "CWU_STANDARD",
    "CWU_WORST_CASE",
    "cross_validate",
    "cross_validate_rooms",
    "DEFAULT_HORIZONS",
    "DEFAULT_OVERFITTING_THRESHOLD",
    "DisturbanceBuilder",
    "GTIModel",
    "EphemerisCalculator",
    "HUBERT_ROOMS",
    "HeatPumpMode",
    "HorizonRMSE",
    "IdentificationReport",
    "InternalGainProfile",
    "IdentificationResult",
    "KalmanEstimator",
    "Measurements",
    "MPCAdapter",
    "MPCConfig",
    "MPCController",
    "MPCInfeasibleError",
    "MPCOptimizer",
    "MPCResult",
    "RecedingHorizonResult",
    "MPC_DT_SECONDS",
    "MPC_HORIZON_STEPS",
    "ModelOrder",
    "OpenMeteoHistorical",
    "Orientation",
    "PIDAdapter",
    "PARAMETRIC_SWEEPS",
    "ProfileKind",
    "QualityMonitor",
    "RCIdentifier",
    "RCModel",
    "RCParams",
    "RoomConfig",
    "RoomReport",
    "S1_FLOOR_OVERHEAT",
    "S2_CONDENSATION",
    "S3_EMERGENCY_HEAT",
    "S4_EMERGENCY_COOL",
    "S5_WATCHDOG",
    "SCENARIO_LIBRARY",
    "SafetyAction",
    "SafetyEvaluator",
    "SafetyRule",
    "SafetyRuleResult",
    "SensorNoise",
    "SensorSnapshot",
    "SimMetrics",
    "SimRecord",
    "SimScenario",
    "SimulatedRoom",
    "SimulationLog",
    "SolarGainModel",
    "SplitCoordinator",
    "SplitDecision",
    "SplitMode",
    "SyntheticWeather",
    "WeatherAPIError",
    "WeatherDataError",
    "WeatherPoint",
    "WeatherRangeError",
    "WeatherSource",
    "WindowConfig",
    "__version__",
    "erbs_decomposition",
    "extraterrestrial_horizontal",
    "create_replay_app",
    "cold_snap",
    "cwu_heavy",
    "cwu_with_splits",
    "dual_source_cold_snap",
    "dual_source_steady_state",
    "extreme_cold",
    "full_year_2025",
    "heavy_construction",
    "hot_july",
    "hubert_real",
    "insulation_sweep",
    "leaky_old_house",
    "load_json",
    "load_pickle",
    "generate_plots",
    "plot_dashboard",
    "plot_overlay",
    "plot_energy",
    "plot_predicted_vs_measured",
    "plot_residuals",
    "plot_rmse_over_time",
    "plot_room_temperatures",
    "plot_splits",
    "plot_valves",
    "plot_weather",
    "priority_inversion_stress",
    "rapid_warming",
    "save_json",
    "save_pickle",
    "screed_sweep",
    "solar_overshoot",
    "steady_state",
    "thin_screed",
    "well_insulated",
]
